export type ReportCategory =
  | 'amphibien'
  | 'bryophyte'
  | 'insecte'
  | 'invertebre'
  | 'mammifere'
  | 'mollusque'
  | 'oiseau'
  | 'plante_vasculaire'
  | 'poisson'
  | 'reptile'

export interface Species {
  category: ReportCategory
  scientificName: string
  commonName: string
  status: string
}

export const SPECIES_DATABASE: readonly Species[] = [
  {
    category: 'amphibien',
    scientificName: 'Desmognathus fuscus',
    commonName: 'Salamandre sombre du Nord',
    status: 'Susceptible',
  },
  {
    category: 'amphibien',
    scientificName: 'Desmognathus ochrophaeus pop. 2',
    commonName: 'Salamandre sombre des montagnes, pop. des Appalaches',
    status: 'Menacée',
  },
  {
    category: 'amphibien',
    scientificName: 'Gyrinophilus porphyriticus pop. 2',
    commonName: 'Salamandre pourpre, pop. des Adirondacks et des Appalaches',
    status: 'Vulnérable',
  },
  {
    category: 'amphibien',
    scientificName: 'Hemidactylium scutatum',
    commonName: 'Salamandre à quatre orteils',
    status: 'Susceptible',
  },
  {
    category: 'amphibien',
    scientificName: 'Lithobates palustris',
    commonName: 'Grenouille des marais',
    status: 'Susceptible',
  },
  {
    category: 'amphibien',
    scientificName: 'Pseudacris maculata',
    commonName: 'Rainette faux-grillon boréale',
    status: 'Susceptible',
  },
  {
    category: 'amphibien',
    scientificName: 'Pseudacris triseriata',
    commonName: "Rainette faux-grillon de l'Ouest",
    status: 'Menacée',
  },
  {
    category: 'bryophyte',
    scientificName: 'Acaulon muticum var. muticum',
    commonName: 'Acaulon mutique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Aloina brevirostris',
    commonName: 'Aloina à bec court',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Andreaea crassinervia',
    commonName: 'Lanterne à nervure épaisse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Andreaea nivalis',
    commonName: 'Lanterne des neiges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Aneura maxima',
    commonName: 'Grand aneura',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Anthoceros agrestis',
    commonName: 'Anthocérote des champs',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Aongstroemia longipes',
    commonName: 'Branchette dressée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Apopellia endiviifolia',
    commonName: 'Pellie ramifiée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Arctoa anderssonii',
    commonName: 'Faux-dicrane arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Asterella tenella',
    commonName: 'Astérelle délicate',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Aulacomnium androgynum',
    commonName: 'Petite aulacomnie',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Biantheridion undulifolium',
    commonName: 'Sylphide ondulée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Brachythecium glaciale',
    commonName: 'Buissonnette des neiges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Brachythecium latifolium',
    commonName: 'Buissonnette à feuilles larges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bruchia flexuosa',
    commonName: 'Bruchie flexueuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum demaretianum',
    commonName: 'Bryum des champs',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum elegans',
    commonName: 'Bryum élégant',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum gemmiparum',
    commonName: 'Bryum gemmipare',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum knowltonii',
    commonName: 'Bryum nordique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum longisetum',
    commonName: 'Bryum à soie longue',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum marratii',
    commonName: 'Bryum furtif',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum rubens',
    commonName: 'Bryum à tubercules rouges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Bryum warneum',
    commonName: 'Bryum marin',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Buxbaumia piperi',
    commonName: 'Gnome mat',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Campylophyllum sommerfeltii',
    commonName: 'Campylie ambiguë',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Campylopus schimperi',
    commonName: 'Torpied arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Campylostelium saxicola',
    commonName: 'Servan des rochers',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Cephaloziella rubella var. sullivantii',
    commonName: 'Céphalozielle bois-pourri',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Cephaloziella uncinata',
    commonName: 'Céphalozielle à crochets',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Ceratodon heterophyllus',
    commonName: 'Cératodon varié',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Cinclidium latifolium',
    commonName: 'Mnie à feuilles larges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Clevea hyalina',
    commonName: 'Morgane évanescente',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Climacium americanum',
    commonName: 'Climacie méridionale',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Ctenidium subrectifolium',
    commonName: 'Hypne papilleuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Cynodontium glaucescens',
    commonName: 'Cynodonte glauque',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Cynodontium schisti',
    commonName: 'Cynodonte arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Dichelyma uncinatum',
    commonName: 'Fontinale à feuilles arquées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Dicranella palustris',
    commonName: 'Dicranelle des marais',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Dicranella staphylina',
    commonName: 'Dicranelle des champs',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Dicranodontium denudatum',
    commonName: 'Dicranodonte effeuillé',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Didymodon maschalogena',
    commonName: 'Pixie arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Diplophyllum obtusatum',
    commonName: 'Fausse-scapanie obtuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Discelium nudum',
    commonName: 'Discélie nue',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Ditrichum pallidum',
    commonName: 'Ditric pâle',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Drepanocladus arcticus',
    commonName: 'Faucillette arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Encalypta affinis subsp. affinis',
    commonName: 'Éteignoir des neiges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Encalypta brevipes',
    commonName: 'Petit éteignoir',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Encalypta longicollis',
    commonName: 'Éteignoir à long col',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Endogemma caespiticia',
    commonName: 'Jongermanne grégaire',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Ephemerum serratum',
    commonName: 'Éphémère à feuilles dentées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Eremonotus myriocarpus',
    commonName: 'Fausse-céphalozielle cuivrée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fissidens exilis',
    commonName: 'Fissident mince',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fissidens fontanus',
    commonName: 'Fissident des sources',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fissidens grandifrons',
    commonName: 'Fissident raide',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fissidens obtusifolius',
    commonName: 'Fissident à feuilles obtuses',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fissidens subbasilaris',
    commonName: 'Fissident obscur',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Forsstroemia trichomitria',
    commonName: 'Hyade à chapeau poilu',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Frullania brittoniae',
    commonName: 'Frullanie papilleuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Frullania inflata var. communis',
    commonName: 'Frullanie enflée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Frullania riparia',
    commonName: 'Frullanie des rochers',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fuscocephaloziopsis catenulata subsp. catenulata',
    commonName: 'Céphalozie chaînon',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Fuscocephaloziopsis macrostachya var. macrostachya',
    commonName: 'Célaphozie des marais',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia atrata',
    commonName: 'Grimmie du cuivre',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia crinitoleucophaea',
    commonName: 'Grimmie ventripotente',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia elongata',
    commonName: 'Grimmie élancée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia incurva',
    commonName: 'Grimmie noire',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia mollis',
    commonName: 'Grimmie à feuilles molles',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia olneyi',
    commonName: 'Grimmie col-de-cygne',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia pilifera',
    commonName: 'Grimmie porte-poil',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia sessitana',
    commonName: 'Grimmie ambiguë',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia teretinervis',
    commonName: 'Grimmie à nervure cylindrique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Grimmia trichophylla',
    commonName: 'Grimmie à feuilles aristées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Gymnocolea inflata subsp. acutiloba',
    commonName: 'Gobelin à lobes aigus',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Gymnomitrion obtusum',
    commonName: 'Gymnomitrion à lobes obtus',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Gymnomitrion revolutum',
    commonName: 'Marsupelle révolutée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Harpanthus drummondii',
    commonName: 'Harpanthe bois-pourri',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hygroamblystegium noterophilum',
    commonName: 'Amblystégie à pointe raide',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hygrobiella laxifolia',
    commonName: 'Hygrobielle à feuilles lâches',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hygrohypnum montanum',
    commonName: 'Riverine des montagnes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hygrohypnum subeugyrium',
    commonName: 'Riverine ovale',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hyophila involuta',
    commonName: 'Hyophile à feuilles enroulées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hypnum andoi',
    commonName: 'Hypne apprimée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Hypnum callichroum',
    commonName: 'Hypne lustrée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Jungermannia atrovirens',
    commonName: 'Jongermanne vert foncé',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Jungermannia polaris',
    commonName: 'Jongermanne polaire',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Kiaeria falcata',
    commonName: 'Faux-dicrane faucille',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Leskea obscura',
    commonName: 'Leskée obscure',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Lophozia silvicola',
    commonName: 'Lophozie des forêts',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Lophozia ventricosa var. uliginosa',
    commonName: 'Lophozie des sphaignes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Mannia fragrans',
    commonName: 'Mannie odorante',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Mannia gracilis',
    commonName: 'Astérelle gracieuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Mannia pilosa',
    commonName: 'Mannie poilue',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Marchantia polymorpha subsp. montivagans',
    commonName: 'Marchantie des montagnes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Marsupella aquatica',
    commonName: 'Marsupelle aquatique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Marsupella boeckii',
    commonName: 'Marsupelle fausse-céphalozielle',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Marsupella condensata',
    commonName: 'Marsupelle pressée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Marsupella sparsifolia',
    commonName: 'Marsupelle arrondie',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Mesoptychia bantriensis',
    commonName: 'Lophozie trompeuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Microlejeunea ulicina',
    commonName: 'Collier des fées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Micromitrium tenerum',
    commonName: 'Éphémère délicat',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Moerckia blyttii‏',
    commonName: 'Collerette des montagnes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Nardia insecta',
    commonName: 'Nardie bilobée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Nardia scalaris',
    commonName: 'Nardie échelonnée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Notothylas orbicularis',
    commonName: 'Anthocérote orbiculaire',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Odontoschisma sphagni',
    commonName: 'Vénusté des sphaignes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Oligotrichum falcatum',
    commonName: 'Polytric à feuilles falciformes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Orthothecium chryseon var. cochleariifolium',
    commonName: 'Stylite cuillère',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Orthotrichum pallens',
    commonName: 'Houppe pâle',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Pelekium minutulum',
    commonName: 'Thuidie minuscule',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Phascum cuspidatum',
    commonName: 'Phasque à feuilles cuspidées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Physcomitrella patens',
    commonName: 'Korrigan à feuilles étalées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Plagiomnium curvatulum',
    commonName: 'Mnie recourbée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Plagiothecium piliferum',
    commonName: 'Satinette porte-poil',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Platylomella lescurii',
    commonName: 'Leskée marginée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Pohlia melanodon',
    commonName: 'Pohlie à dents noires',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Polytrichastrum ohioense',
    commonName: 'Polytric méridional',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Pseudocalliergon brevifolium',
    commonName: 'Pseudocalliergon à feuilles courtes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Pseudoleskea patens',
    commonName: 'Leskée étalée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Pseudoleskea stenophylla',
    commonName: 'Leskée à feuilles étroites',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Psilopilum cavifolium',
    commonName: 'Polytric à feuilles concaves',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Pterygoneurum ovatum',
    commonName: 'Nisse ovale',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Racomitrium canescens subsp. latifolium',
    commonName: 'Frangine à feuilles larges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Racomitrium elongatum',
    commonName: 'Frangine élancée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Racomitrium panschii',
    commonName: 'Frangine arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Rhizomnium andrewsianum',
    commonName: 'Mnie ondulée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Rhytidiadelphus loreus',
    commonName: 'Ébouriffe lanière',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Riccia beyrichiana',
    commonName: 'Riccie frangée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Riccia bifurca',
    commonName: 'Riccie fourchue',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Riccia cavernosa',
    commonName: 'Riccie caverneuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Riccia frostii',
    commonName: 'Riccie à marges rouges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Riccia rhenana',
    commonName: 'Riccie précieuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Riccia sorocarpa',
    commonName: 'Riccie grisâtre',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Saccobasis polita',
    commonName: 'Tritomaire élégante',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sanionia orthothecioides',
    commonName: 'Faucillette faux-stylite',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sauteria alpina',
    commonName: 'Sautérie alpine',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania carinthiaca var. carinthiaca',
    commonName: 'Scapanie bois-pourri',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania glaucocephala var. glaucocephala',
    commonName: 'Scapanie glauque',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania irrigua subsp. rufescens',
    commonName: 'Scapanie des plages',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania kaurinii',
    commonName: 'Scapanie inusitée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania ligulifolia',
    commonName: 'Scapanie à feuilles ligulées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania pseudocalcicola',
    commonName: 'Scapanie calcicole',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Scapania scandica',
    commonName: 'Scapanie à petites feuilles',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium atrichum',
    commonName: 'Grimmie glabre',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium crassipilum',
    commonName: 'Grimmie à soie épaisse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium cryptocarpum',
    commonName: 'Grimmie à capsule cachée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium flexipile',
    commonName: 'Grimmie variable',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium frigidum',
    commonName: 'Grimmie des montagnes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium grandirete',
    commonName: 'Grimmie rougeâtre',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium holmenianum',
    commonName: 'Grimmie des tourbières',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium pulchrum',
    commonName: 'Grimmie ravissante',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistidium venetum',
    commonName: 'Grimmie azurée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Schistochilopsis grandiretis',
    commonName: 'Lophozie à ventre noir',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Seligeria brevifolia',
    commonName: 'Séligérie à feuilles courtes',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Seligeria diversifolia',
    commonName: 'Séligérie à feuilles variées',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Seligeria recurvata',
    commonName: 'Séligérie à soie courbée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum aongstroemii',
    commonName: "Sphaigne d'Angström",
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum austinii',
    commonName: "Sphaigne d'Austin",
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum mirum',
    commonName: 'Sphaigne étrange',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum molle',
    commonName: 'Sphaigne molle',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum orientale',
    commonName: 'Sphaigne orientale',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum perfoliatum',
    commonName: 'Sphaigne perfoliée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum rubiginosum',
    commonName: 'Sphaigne panachée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Sphagnum strictum',
    commonName: 'Sphaigne dressée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Splachnum pensylvanicum',
    commonName: 'Splanc étroit',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Stegonia latifolia var. latifolia',
    commonName: 'Stégonie à feuilles larges',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Stegonia latifolia var. pilifera',
    commonName: 'Stégonie porte-poil',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tayloria acuminata',
    commonName: 'Taylorie acuminée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tayloria splachnoides',
    commonName: 'Taylorie faux-splanc',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tetraplodon pallidus',
    commonName: 'Tétraplodon pâle',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tetrodontium brownianum',
    commonName: 'Quadrident variable',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tetrodontium ovatum',
    commonName: 'Quadrident ovale',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tetrodontium repandum',
    commonName: 'Quadrident ondulé',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Thelia asprella',
    commonName: 'Thélie papilleuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Thelia hirtella',
    commonName: 'Thélie hirsute',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Timmia norvegica var. excurrens',
    commonName: 'Timmie à nervure excurrente',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Timmia sibirica',
    commonName: 'Timmie papilleuse',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tortella inclinata',
    commonName: 'Tortelle inclinée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tortula laureri',
    commonName: 'Tortule de Laurer',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tortula leucostoma',
    commonName: 'Tortule blanche',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tortula nevadensis',
    commonName: 'Tortule édentée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Trichostomum arcticum',
    commonName: 'Trichostome arctique',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tritomaria capitata',
    commonName: 'Lophozie des sables',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tritomaria laxa',
    commonName: 'Lophozie lâche',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Tritomaria quinquedentata subsp. turgida',
    commonName: 'Tritomaire enflée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Weissia muhlenbergiana',
    commonName: 'Weissie à capsule immergée',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Weissia phascopsis',
    commonName: 'Weissie faux-phasque',
    status: 'Susceptible',
  },
  {
    category: 'bryophyte',
    scientificName: 'Zygodon rupestris',
    commonName: 'Houppe des rochers',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Acronicta rubricoma',
    commonName: 'Acronicte à virgules rougeâtres',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Adalia bipunctata',
    commonName: 'Coccinelle à deux points',
    status: 'Vulnérable',
  },
  {
    category: 'insecte',
    scientificName: 'Adela caeruleella',
    commonName: 'Fée noire aux longues antennes',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Aeshna clepsydra',
    commonName: 'Aeschne clepsydre',
    status: 'Candidate',
  },
  {
    category: 'insecte',
    scientificName: 'Bombus affinis',
    commonName: 'Bourdon à tache rousse',
    status: 'Menacée',
  },
  {
    category: 'insecte',
    scientificName: 'Bombus bohemicus',
    commonName: 'Bourdon-coucou grisonnant',
    status: 'Candidate',
  },
  {
    category: 'insecte',
    scientificName: 'Bombus terricola',
    commonName: 'Bourdon-perceur septentrional',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Cephaloon ungulare',
    commonName: 'Faux-longicorne scalaire',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Cicindela lepida',
    commonName: 'Cicindèle blanche',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Cicindela patruela',
    commonName: 'Cicindèle verte des pinèdes',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Coccinella novemnotata',
    commonName: 'Coccinelle à neuf points',
    status: 'Menacée',
  },
  {
    category: 'insecte',
    scientificName: 'Coenonympha nipisiquit',
    commonName: 'Satyre fauve des Maritimes',
    status: 'Menacée',
  },
  {
    category: 'insecte',
    scientificName: 'Erynnis martialis',
    commonName: 'Hespérie tachetée',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Erythemis simplicicollis',
    commonName: 'Érythème des étangs',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Erythrodiplax berenice',
    commonName: 'Érythrodiplax côtier',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Euphyes dion',
    commonName: 'Hespérie de Dionée',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Euptoieta claudia',
    commonName: 'Fritillaire panachée',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Gomphaeschna furcillata',
    commonName: 'Aeschne pygmée',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Gomphurus ventricosus',
    commonName: 'Gomphe ventru',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Lestes vigilax',
    commonName: 'Leste matinal',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Lycaena dospassosi',
    commonName: 'Cuivré des marais salés',
    status: 'Menacée',
  },
  {
    category: 'insecte',
    scientificName: 'Melanoplus gaspesiensis',
    commonName: 'Mélanople de Gaspésie',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Merhynchites bicolor',
    commonName: 'Charançon bicolor du rosier',
    status: 'Candidate',
  },
  {
    category: 'insecte',
    scientificName: 'Nasiaeschna pentacantha',
    commonName: 'Æschne Cyrano',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Neospondylis upiformis',
    commonName: 'Spondyle ténébrion',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Oeneis bore gaspeensis',
    commonName: 'Nordique à nervures blanches de Gaspé',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Ophiogomphus anomalus',
    commonName: 'Ophiogomphe bariolé',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Phanogomphus quadricolor',
    commonName: 'Gomphe des fosses',
    status: 'Candidate',
  },
  {
    category: 'insecte',
    scientificName: 'Phymatodes maculicollis',
    commonName: 'Phymatode à col maculé',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Poanes massasoit',
    commonName: 'Hespérie des roseaux',
    status: 'Candidate',
  },
  {
    category: 'insecte',
    scientificName: 'Pompeius verna',
    commonName: 'Hespérie à taches vitreuses',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Somatochlora incurvata',
    commonName: 'Cordulie incurvée',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Stylurus amnicola',
    commonName: 'Gomphe riverin',
    status: 'Candidate',
  },
  {
    category: 'insecte',
    scientificName: 'Sympetrum corruptum',
    commonName: 'Sympétrum bagarreur',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Trechus crassiscapus',
    commonName: 'Tréchine à scapes larges',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Williamsonia fletcheri',
    commonName: 'Cordulie bistrée',
    status: 'Susceptible',
  },
  {
    category: 'insecte',
    scientificName: 'Xyloryctes jamaicensis',
    commonName: 'Dynaste rhinocéros',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Aeorestes cinereus',
    commonName: 'Chauve-souris cendrée',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Balaenoptera musculus',
    commonName: 'Rorqual bleu',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Balaenoptera physalus',
    commonName: 'Rorqual commun',
    status: 'Vulnérable',
  },
  {
    category: 'mammifere',
    scientificName: 'Delphinapterus leucas pop. 1',
    commonName: "Béluga, pop. de l'Est de la baie d'Hudson",
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Delphinapterus leucas pop. 2',
    commonName: "Béluga, pop. de la baie d'Ungava",
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Delphinapterus leucas pop. 3',
    commonName: "Béluga, pop. de l'estuaire du Saint-Laurent",
    status: 'Menacée',
  },
  {
    category: 'mammifere',
    scientificName: 'Eubalaena glacialis',
    commonName: 'Baleine noire',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Glaucomys volans pop. 1',
    commonName: 'Petit polatouche, pop. des plaines des Grands Lacs',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Gulo gulo',
    commonName: 'Carcajou',
    status: 'Menacée',
  },
  {
    category: 'mammifere',
    scientificName: 'Lasionycteris noctivagans',
    commonName: 'Chauve-souris argentée',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Lasiurus borealis',
    commonName: "Chauve-souris rousse de l'Est",
    status: 'Vulnérable',
  },
  {
    category: 'mammifere',
    scientificName: 'Microtus chrotorrhinus',
    commonName: 'Campagnol des rochers',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Microtus pinetorum',
    commonName: 'Campagnol sylvestre',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Mustela nivalis',
    commonName: 'Belette pygmée',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Myotis leibii',
    commonName: "Chauve-souris pygmée de l'Est",
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Myotis lucifugus',
    commonName: 'Petite chauve-souris brune',
    status: 'Menacée',
  },
  {
    category: 'mammifere',
    scientificName: 'Myotis lucifugus, complexe Myotis',
    commonName: 'Complexe Myotis',
    status: 'Candidate',
  },
  {
    category: 'mammifere',
    scientificName: 'Myotis septentrionalis',
    commonName: 'Chauve-souris nordique',
    status: 'Menacée',
  },
  {
    category: 'mammifere',
    scientificName: 'Odobenus rosmarus pop. 4',
    commonName:
      "Morse de l'Atlantique, pop. du centre de l'Arctique et du Bas-Arctique",
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Perimyotis subflavus',
    commonName: "Pipistrelle de l'Est",
    status: 'Menacée',
  },
  {
    category: 'mammifere',
    scientificName: 'Phoca vitulina mellonae',
    commonName: 'Phoque commun des lacs des Loups Marins',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Phocoena phocoena',
    commonName: 'Marsouin commun',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Puma concolor',
    commonName: 'Cougar',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Rangifer tarandus caribou pop. 14',
    commonName: 'Caribou des bois, écotype forestier',
    status: 'Vulnérable',
  },
  {
    category: 'mammifere',
    scientificName: 'Rangifer tarandus caribou pop. 2',
    commonName: 'Caribou des bois, écotype montagnard, pop. de la Gaspésie',
    status: 'Menacée',
  },
  {
    category: 'mammifere',
    scientificName: 'Sorex dispar',
    commonName: 'Musaraigne longicaude',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Sorex gaspensis',
    commonName: 'Musaraigne de Gaspé',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Synaptomys cooperi',
    commonName: 'Campagnol-lemming de Cooper',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'Ursus americanus pop. 1',
    commonName: "Ours noir de l'île d'Anticosti",
    status: 'Candidate',
  },
  {
    category: 'mammifere',
    scientificName: 'Ursus maritimus',
    commonName: 'Ours blanc',
    status: 'Vulnérable',
  },
  {
    category: 'mollusque',
    scientificName: 'Acroloxus coloradensis pop. 2',
    commonName: 'Patelle d’eau douce pointue, pop. de l’Est',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Alasmidonta marginata',
    commonName: 'Alasmidonte rugueuse',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Birgella subglobosus',
    commonName: 'Somatogyre globuleux',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Elliptio crassidens',
    commonName: 'Elliptio à dents fortes',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Eurynia dilatata',
    commonName: 'Elliptio pointu',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Lasmigona compressa',
    commonName: 'Lasmigone des ruisseaux',
    status: 'Candidate',
  },
  {
    category: 'mollusque',
    scientificName: 'Leptodea fragilis',
    commonName: 'Leptodée fragile',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Ligumia recta',
    commonName: 'Ligumie noire',
    status: 'Candidate',
  },
  {
    category: 'mollusque',
    scientificName: 'Margaritifera margaritifera',
    commonName: "Mulette-perlière de l'Est",
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Obovaria olivaria',
    commonName: 'Obovarie olivâtre',
    status: 'Menacée',
  },
  {
    category: 'mollusque',
    scientificName: 'Potamilus alatus',
    commonName: 'Potamile ailé',
    status: 'Susceptible',
  },
  {
    category: 'mollusque',
    scientificName: 'Utterbackia imbecillis',
    commonName: 'Anodonte papyracée',
    status: 'Candidate',
  },
  {
    category: 'mollusque',
    scientificName: 'Utterbackiana implicata',
    commonName: 'Anodonte du gaspareau',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Ammodramus savannarum pratensis',
    commonName: 'Bruant sauterelle pratensis',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Ammospiza nelsoni',
    commonName: 'Bruant de Nelson',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Antrostomus vociferus',
    commonName: 'Engoulevent bois-pourri',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Aquila chrysaetos',
    commonName: 'Aigle royal',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Asio flammeus',
    commonName: 'Hibou des marais',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Bucephala islandica pop. 1',
    commonName: "Garrot d'Islande, pop. de l'Est",
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Calidris canutus rufa',
    commonName: 'Bécasseau maubèche rufa',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Calidris subruficollis',
    commonName: 'Bécasseau roussâtre',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Cardellina canadensis',
    commonName: 'Paruline du Canada',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Catharus bicknelli',
    commonName: 'Grive de Bicknell',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Chaetura pelagica',
    commonName: 'Martinet ramoneur',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Charadrius melodus melodus',
    commonName: 'Pluvier siffleur melodus',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Chlidonias niger',
    commonName: 'Guifette noire',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Chordeiles minor',
    commonName: "Engoulevent d'Amérique",
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Cistothorus stellaris',
    commonName: 'Troglodyte à bec court',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Contopus cooperi',
    commonName: 'Moucherolle à côtés olive',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Contopus virens',
    commonName: "Pioui de l'Est",
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Coturnicops noveboracensis',
    commonName: 'Râle jaune',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Dolichonyx oryzivorus',
    commonName: 'Goglu des prés',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Euphagus carolinus',
    commonName: 'Quiscale rouilleux',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Falco peregrinus pop. 1',
    commonName: 'Faucon pèlerin anatum/tundrius',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Haliaeetus leucocephalus',
    commonName: 'Pygargue à tête blanche',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Hirundo rustica',
    commonName: 'Hirondelle rustique',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Histrionicus histrionicus pop. 1',
    commonName: "Arlequin plongeur, pop. de l'Est",
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Hydrobates leucorhous pop. 1',
    commonName: 'Océanite cul-blanc, pop. de l’Atlantique',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Hydroprogne caspia',
    commonName: 'Sterne caspienne',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Hylocichla mustelina',
    commonName: 'Grive des bois',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Ixobrychus exilis',
    commonName: 'Petit blongios',
    status: 'Vulnérable',
  },
  {
    category: 'oiseau',
    scientificName: 'Lanius ludovicianus pop. 1',
    commonName: "Pie-grièche migratrice, sous-espèce de l'Est",
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Loxia curvirostra percna',
    commonName: 'Bec-croisé des sapins percna',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Melanerpes erythrocephalus',
    commonName: 'Pic à tête rouge',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Parkesia motacilla',
    commonName: 'Paruline hochequeue',
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Podiceps auritus',
    commonName: 'Grèbe esclavon',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Progne subis',
    commonName: 'Hirondelle noire',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Riparia riparia',
    commonName: 'Hirondelle de rivage',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Setophaga cerulea',
    commonName: 'Paruline azurée',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Sterna dougallii',
    commonName: 'Sterne de Dougall',
    status: 'Menacée',
  },
  {
    category: 'oiseau',
    scientificName: 'Sturnella magna',
    commonName: 'Sturnelle des prés',
    status: 'Candidate',
  },
  {
    category: 'oiseau',
    scientificName: 'Tyto alba pop. 2',
    commonName: "Effraie des clochers, pop. de l'Est",
    status: 'Susceptible',
  },
  {
    category: 'oiseau',
    scientificName: 'Vermivora chrysoptera',
    commonName: 'Paruline à ailes dorées',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Acipenser fulvescens',
    commonName: 'Esturgeon jaune',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Acipenser oxyrinchus',
    commonName: 'Esturgeon noir',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Alosa sapidissima',
    commonName: 'Alose savoureuse',
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Ameiurus natalis',
    commonName: 'Barbotte jaune',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Ammocrypta pellucida',
    commonName: 'Dard de sable',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Anarhichas denticulatus',
    commonName: 'Loup à tête large',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Anarhichas lupus',
    commonName: 'Loup atlantique',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Anarhichas minor',
    commonName: 'Loup tacheté',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Anguilla rostrata',
    commonName: "Anguille d'Amérique",
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Brosme brosme',
    commonName: 'Brosme',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Coregonus artedi pop. 1',
    commonName: 'Cisco de printemps',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Esox americanus vermiculatus',
    commonName: 'Brochet vermiculé',
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Esox niger',
    commonName: 'Brochet maillé',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Etheostoma caeruleum',
    commonName: 'Dard arc-en-ciel',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Gadus morhua pop. 4',
    commonName: 'Morue franche, pop. nord-laurentienne',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Gadus morhua pop. 7',
    commonName: 'Morue franche, pop. sud-laurentienne',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Hybognathus hankinsoni',
    commonName: 'Méné laiton',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Ichthyomyzon fossor',
    commonName: 'Lamproie du Nord',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Lamna nasus',
    commonName: 'Maraîche',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Lepomis peltastes',
    commonName: 'Crapet du Nord',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Leucoraja ocellata pop. 5',
    commonName: 'Raie tachetée, pop. du golfe du Saint-Laurent',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Moxostoma carinatum',
    commonName: 'Chevalier de rivière',
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Moxostoma hubbsi',
    commonName: 'Chevalier cuivré',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Myoxocephalus quadricornis',
    commonName: 'Chaboisseau à quatre cornes',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Myoxocephalus thompsonii',
    commonName: 'Chabot de profondeur',
    status: 'Menacée',
  },
  {
    category: 'poisson',
    scientificName: 'Notropis bifrenatus',
    commonName: "Méné d'herbe",
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Notropis rubellus',
    commonName: 'Méné à tête rose',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Noturus flavus',
    commonName: 'Chat-fou des rapides',
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Noturus insignis',
    commonName: 'Chat-fou liséré',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Osmerus mordax pop. 1',
    commonName:
      "Éperlan arc-en-ciel, pop. du sud de l'estuaire du Saint-Laurent",
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Percina copelandi',
    commonName: 'Fouille-roche gris',
    status: 'Vulnérable',
  },
  {
    category: 'poisson',
    scientificName: 'Prionace glauca',
    commonName: 'Requin bleu',
    status: 'Susceptible',
  },
  {
    category: 'poisson',
    scientificName: 'Salvelinus alpinus oquassa',
    commonName: 'Omble chevalier oquassa',
    status: 'Vulnérable',
  },
  {
    category: 'reptile',
    scientificName: 'Apalone spinifera',
    commonName: 'Tortue-molle à épines',
    status: 'Menacée',
  },
  {
    category: 'reptile',
    scientificName: 'Chelydra serpentina',
    commonName: 'Tortue serpentine',
    status: 'Candidate',
  },
  {
    category: 'reptile',
    scientificName: 'Clemmys guttata',
    commonName: 'Tortue ponctuée',
    status: 'Susceptible',
  },
  {
    category: 'reptile',
    scientificName: 'Dermochelys coriacea',
    commonName: 'Tortue luth',
    status: 'Menacée',
  },
  {
    category: 'reptile',
    scientificName: 'Diadophis punctatus edwardsii',
    commonName: 'Couleuvre à collier du Nord',
    status: 'Susceptible',
  },
  {
    category: 'reptile',
    scientificName: 'Emydoidea blandingii',
    commonName: 'Tortue mouchetée',
    status: 'Menacée',
  },
  {
    category: 'reptile',
    scientificName: 'Glyptemys insculpta',
    commonName: 'Tortue des bois',
    status: 'Vulnérable',
  },
  {
    category: 'reptile',
    scientificName: 'Graptemys geographica',
    commonName: 'Tortue géographique',
    status: 'Vulnérable',
  },
  {
    category: 'reptile',
    scientificName: 'Lampropeltis triangulum',
    commonName: 'Couleuvre tachetée',
    status: 'Vulnérable',
  },
  {
    category: 'reptile',
    scientificName: 'Nerodia sipedon sipedon',
    commonName: "Couleuvre d'eau du Nord",
    status: 'Vulnérable',
  },
  {
    category: 'reptile',
    scientificName: 'Opheodrys vernalis',
    commonName: 'Couleuvre verte',
    status: 'Susceptible',
  },
  {
    category: 'reptile',
    scientificName: 'Sternotherus odoratus',
    commonName: 'Tortue musquée',
    status: 'Menacée',
  },
  {
    category: 'reptile',
    scientificName: 'Storeria dekayi',
    commonName: 'Couleuvre brune',
    status: 'Menacée',
  },
  {
    category: 'reptile',
    scientificName: 'Thamnophis saurita septentrionalis',
    commonName: 'Couleuvre mince du Nord',
    status: 'Susceptible',
  },
  {
    category: 'mammifere',
    scientificName: 'A déterminer',
    commonName: 'Chauve-souris (non identifiée)',
    status: 'non',
  },
  {
    category: 'amphibien',
    scientificName: 'A déterminer',
    commonName: 'Salamandre (non identifiée)',
    status: 'non',
  },
  {
    category: 'reptile',
    scientificName: 'A déterminer',
    commonName: 'Couleuvre (non identifiée)',
    status: 'non',
  },
  {
    category: 'reptile',
    scientificName: 'A déterminer',
    commonName: 'Tortue (non identifié)',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'A déterminer',
    commonName: 'Oiseau (non identifié)',
    status: 'non',
  },
  {
    category: 'mammifere',
    scientificName: 'Mustela erminea',
    commonName: 'Hermine',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Butorides virescens',
    commonName: 'Héron vert',
    status: 'non',
  },
  {
    category: 'mammifere',
    scientificName: 'Canis latrans',
    commonName: 'Coyote',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Megaceryle alcyon',
    commonName: 'Martin pêcheur',
    status: 'non',
  },
  {
    category: 'insecte',
    scientificName: 'Danaus plexippus',
    commonName: 'Papillon monarque',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Setophaga coronata',
    commonName: 'Paruline à croupion jaune',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Otus asio',
    commonName: 'Petit duc maculé',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Aegolius acadicus',
    commonName: 'Petite nyctale',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Haliaeetus leucocephalus',
    commonName: 'Pyguarge à tête blanche',
    status: 'non',
  },
  {
    category: 'mammifere',
    scientificName: 'Procyon lotor',
    commonName: 'Raton-laveur',
    status: 'non',
  },
  {
    category: 'mammifere',
    scientificName: 'vulpes fulva',
    commonName: 'Renard roux',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Regulus calendula',
    commonName: 'Roitelet à couronne rubis',
    status: 'non',
  },
  {
    category: 'amphibien',
    scientificName: 'Ambystoma laterale',
    commonName: 'Salamandre à points bleues',
    status: 'non',
  },
  {
    category: 'amphibien',
    scientificName: 'Plethodon cinereus',
    commonName: 'Salamandre cendrée',
    status: 'non',
  },
  {
    category: 'amphibien',
    scientificName: 'Notophthalmus viridescens',
    commonName: 'Triton vert',
    status: 'non',
  },
  {
    category: 'mammifere',
    scientificName: 'Mustela vison',
    commonName: "Vison d'Amérique",
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Nycticorax nycticorax',
    commonName: 'Bihoreau gris',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Circus hudsonius',
    commonName: 'Busard des marais',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Aix sponsa',
    commonName: 'Canard branchu',
    status: 'non',
  },
  {
    category: 'mammifere',
    scientificName: 'Eptesicus fuscus',
    commonName: 'Chauve-souris brune (grande)',
    status: 'non',
  },
  {
    category: 'insecte',
    scientificName: 'Danaus plexippus',
    commonName: 'Chenille de monarque',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Surnia ulula',
    commonName: 'Chouette épervière',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Strix varia',
    commonName: 'Chouette rayée',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Archilochus colubris',
    commonName: 'Colibri à gorge rubis',
    status: 'non',
  },
  {
    category: 'reptile',
    scientificName: 'Storeria occipitomaculata',
    commonName: 'Couleuvre à ventre rouge',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Falco sparverius',
    commonName: "Crécerelle d'Amérique",
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Accipiter cooperii',
    commonName: 'Épervier de Cooper',
    status: 'non',
  },
  {
    category: 'oiseau',
    scientificName: 'Bubo virginianus',
    commonName: "Grand duc d'Amérique",
    status: 'non',
  },
  {
    category: 'amphibien',
    scientificName: 'Rana sylvatica',
    commonName: 'Grenouille des bois',
    status: 'non',
  },
] as const

function normalizeText(text: string): string {
  return text.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
}

export function getSpeciesByCategory(category: ReportCategory): Species[] {
  return SPECIES_DATABASE.filter((s) => s.category === category)
}

export function searchSpecies(
  query: string,
  category?: ReportCategory,
  limit: number = 20,
): Species[] {
  if (!query.trim()) {
    return []
  }

  const normalizedQuery = normalizeText(query)
  let candidates = SPECIES_DATABASE

  if (category) {
    candidates = candidates.filter((s) => s.category === category)
  }

  const results = candidates
    .map((species) => {
      const normalizedCommon = normalizeText(species.commonName)
      const normalizedScientific = normalizeText(species.scientificName)

      const commonPrefixMatch = normalizedCommon.startsWith(normalizedQuery)
      const scientificPrefixMatch =
        normalizedScientific.startsWith(normalizedQuery)
      const commonSubstringMatch = normalizedCommon.includes(normalizedQuery)
      const scientificSubstringMatch =
        normalizedScientific.includes(normalizedQuery)

      let score = 0
      if (commonPrefixMatch) score = 4
      else if (scientificPrefixMatch) score = 3
      else if (commonSubstringMatch) score = 2
      else if (scientificSubstringMatch) score = 1
      else score = 0

      return { species, score }
    })
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((item) => item.species)

  return results
}
